### ISSUE TITLE
Issuing commands via the MC Server console

### ISSUE THREAD

**Issue by richraid21** [itzg/dockerfiles#134]
Hi, 

Is it possible to execute commands via the server console?

I've tried `docker attach <container>` and once in, my command just hangs so I don't think I'm doing it correctly. 

Thanks

**Comment by itzg** [comment]
@richraid21 , double check that you included the `-i` and `-t` arguments when doing the `docker run` since that's the chance to declare TTY and open stdin.

If that still isn't cooperating and you want to use a version of Minecraft that supports RCON, then this awesome web app I found recently might help you too:

https://brainfoolong.github.io/rcon-web-admin/

I wrapped a docker image around that 

https://hub.docker.com/r/itzg/rcon/

and with this section added to my compose file that I use for regression testing

https://github.com/itzg/dockerfiles/blob/master/minecraft-server/docker-compose.yml#L17-L23

I can now go to the rcon web app and happily interact with the minecraft server without having to mess with attaching, etc :)

**Comment by itzg** [comment]
@richraid21 ...there is also now the ability to use an RCON CLI integrated with the image, such as:

```
docker exec $ID rcon-cli stop
```

Is this still an issue for you?

**Comment by itzg** [comment]
Please re-open if this is still an issue for you.
