### ISSUE TITLE
[minecraft] feature request: Handle upgrade of server 

### ISSUE THREAD

**Issue by TheLeftMoose** [itzg/dockerfiles#198]
So, upgrading a server can be some kind of a challenge since this image is so diverse as it is.

I see in previous issues that the only really way to do an upgrade, is to delete the server jar file, and then boot the container. This should trigger either a download or run of spigot buildtools.

Though, this approach is kinda painful, since you will need to do something by hand; It would be more nice if it was possible to pass some kind of argument that triggers an upgrade.

Any thoughts about this suggestion?

**Comment by itzg** [comment]
I agree this seems very useful and also agree that manually deleting the jar in order to trigger the upgrade feels wrong/painful. The quirky part of addressing this is that the environment variables and command line arguments of the container are established at `docker run` or `docker create` time. After that point I don't believe they can be changed. Things like `docker-compose` give the illusion of changing those values, but it actually re-creates the container and re-attaches the previous container's volumes.

So...I'd have to think and research more, but likewise I'm to open to suggestions.

**Comment by TheLeftMoose** [comment]
We could make a env like UPGRADE_TO.

If set to latest, then script will always upgrade to latest version available

If set to specific version then, 
  ifelse newer than running version, then upgrade to specific version
  ifelse older, then do nothing

challenges:
* do we know if there is a new version of any of the servers that is supported in this docker image at all?

**Comment by itzg** [comment]
Since I'm enjoying the latest snapshots, I was happy to see that when using `VERSION=LATEST` or `VERSION=SNAPSHOT` it will always download the newest server version, respectively. For example scaled this service to 0 and back to 1 replica and it picked up the newer snapshot jar:

```
mc-snapshot.1.ljix79cyqksb@nuc    | Switching to user 'minecraft'
mc-snapshot.1.ljix79cyqksb@nuc    | Checking version information.
mc-snapshot.1.ljix79cyqksb@nuc    | Checking type information.
mc-snapshot.1.ljix79cyqksb@nuc    | Downloading minecraft_server.18w09a.jar ...
```

Granted, this doesn't help the scenario where you have pinned `VERSION` to a specific one and want to upgrade to another.
