### ISSUE TITLE
Server-Icon

### ISSUE THREAD

**Issue by robinbraemer** [itzg/dockerfiles#206]
https://github.com/itzg/dockerfiles/blob/2627317e03617fbe4de424e2effcd63df9798a46/minecraft-server/start-minecraftFinalSetup#L15

it is a server-icon.png > see https://www.spigotmc.org/wiki/server-icon/

**Comment by itzg** [comment]
If you’re referring to the comment, it’s because the user is allowed to point to anything out on the internet but hopefully at least an image file. The comment is saying that the script doesn’t know at download time if it’s a PNG, GIF, JPEG, etc so just give a suffix “img” until it is evaluated and converted into a PNG.
