### ISSUE TITLE
Environment properties inforcement problem

### ISSUE THREAD

**Issue by audebruin** [itzg/dockerfiles#234]
Could it be that the environment properties are not inforced correctly?

I setup GID and UID in the Docker container environment, but its failed to write to the data folder. CHOWN and CHMOD is properly in place. Got the error: 
"ERROR: unable to write eula to /data. Please make sure attached directory is writable by uid=1024"

When i remove the GID and UID, changed ownership data folder to full control everyone. Manually added eula.txt. When run it tries to write with 1000:1000 but it gives the error: 
"[Server thread/INFO]: Generating new properties file"
"[Server thread/WARN]: Failed to save server.properties"
"java.io.FileNotFoundException: server.properties (Permission denied)"

I do not have this problem with the nov 2017 build.

Synology NAS 216+
Docker version 17.05.0-ce, Synology build
Latest build (19 July 2018)

**Comment by itzg** [comment]
Relatively recently I did change the image to not run as root in order to follow recommended security practices, however that eliminated the ability to use the UID/GID environment variables. I’m still thinking through a compromise or options for security va flexibility. 

To that end, with the latest image pulled, can you grab and provide the very first line of output that says “Running as”. I added that to help diagnose these cases where container uid and volume ownership are aligned. Thanks.

**Comment by audebruin** [comment]
@itzg Log says: Running as '1000:1000' with /data as 'drwxrwxrwx    1 1024     100            170 Jul 21 11:23 /data'

**Comment by itzg** [comment]
I'm not finding any information on how to do the equivalent of `docker run --user 1024`, so it looks like I'll have to revert to starting the container as root and using `UID` and `GID` variables to drop privileges.

**Comment by itzg** [comment]
I have pushed the change to Hub that brings back the UID and GID options:

https://github.com/itzg/dockerfiles/blob/master/minecraft-server/README.md#running-as-alternate-usergroup-id
