### ISSUE TITLE
Move the java invocation out of start-minecraftFinalSetup

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [itzg/dockerfiles#274]
The immediate java call in start-minecraftFinalSetup is unhelpful for situations where the log4j2 config needs to be modified (and requires more classpath additions). Would be helpful if we could customize the invocation.

Example: `java -classpath lib/*:server.jar -Xmx512M -Xms512M -Dlog4j.configurationFile=log4j2.xml net.minecraft.server.MinecraftServer nogui`

This invocation is necessary when using, say, JsonLayout log appenders.

**Comment by itzg** [comment]
There are a few ways to pass additional arguments into the java invocation. JVM arguments, such as the `-classpath lib/*` and `-Dlog4j.configurationFile=log4j2.xml` can be passed via the `JVM_OPTS` environment variable, which is documented [here](https://github.com/itzg/dockerfiles/blob/master/minecraft-server/README.md#jvm-options).

What I haven't documented is that all additional arguments passed after the image are also passed along to the java invocation. You can also pass arguments, such as `nogui` via the `EXTRA_ARGS` environment variable; however, `nogui` is a bad example since it is already included by default, but can be disabled by setting `GUI=false`.

**Comment by itzg** [comment]
@VTCAKAVSMoACE do those options work for you?

**Comment by VTCAKAVSMoACE** [comment]
For whatever reason, those options do not work for me. I am still trying to determine why that is the case. I had previously attempted to use that method, but I suspect that argument expansion in the classpath argument is ignored. I have simply modified the start script in my case.

That being said, for other setups (such as non-Java Minecraft implementations), this may not be the best solution. I don't think this is a huge priority, but it might be a future consideration.
