### ISSUE TITLE
[feature] [minecraft-server] Allow passing of world data to server

### ISSUE THREAD

**Issue by sshipway** [itzg/dockerfiles#48]
The minecraft-server container is very flexible, but one thing missing is the ability to pas a preexisting world without having to manage the storage.

It would be good to be able to pass `-e WORLD=url` and have the container download a zipfile from the specified URL and unpack it into the /data/world directory.  This would allow using ephemeral copies of archived worlds (eg, Hunger Games worlds) that would be copied, and then deleted after the server exited.  You could also use this in multiple instances then without needing multiple storage.

Should be pretty simple to do, if nobody else does it, I might make a pull req later...

**Comment by itzg** [comment]
Excellent idea! If I can't get to it in the next few days, then go for it.

**Comment by sshipway** [comment]
In fact, the whole idea was so good, I've already forked the repo and done some work on it.  I'll run a bit more testing and write the necessary documentation to the README before I submit the pull request, but in brief : 
- Changed server.properties to default command blocks enabled
- Add volumes for /mods and /config that, if mounted and non-empty, will have their contents copied to /data/mods and /data/config.  This allows you to  specify mods (using a read-only shared volume) without having to mount /data as readwrite
- Create empty banned-players.json and banned-ip.json to prevent error message
- Allow WORLD env var to specify a URL that is used to download world data in a zip file.  The zip is expanded in the /data dir, so it can contain a customised server.properties or even mods, if necessary.  If the zip does not contain a world/ directory, then it is searched for a level.dat and the parent dir is renamed to world/, which allows it to work with the normal save format used on archive sites.

This lets you do something like
````
docker run -t -i -p 25565:25565 --rm=true -e EULA=true \
  -e WORLD=http://myhost/worlds/MyWorld.zip itzg/minecraft-server
````
... and it will spin up a server for (eg) your hunger games play, and delete everything once the game is over and the server shut down.

I'm now looking at making a container with a web frontend to spin these up on demand, giving you an easy selection of available worlds and options, so that the kids don't need to keep asking me to do it for them (laziness is the mother of invention, they say)

This is a very useful container, and I was surprised how simple but effective it is.  I've been using it for all my demos at work because it can show a tcp-based non-web application (at least that's my excuse.  I've actually managed to make it my job to play minecraft...)

**Comment by itzg** [comment]
That's so exciting. I'm looking forward to the pull request.

I'd be very interested in using (and contributing to) a web frontend. I had a false-start with [this project](https://github.com/itzg/minecraft-container-yard) -- it was before Machine and Swarm existed/matured and I had discovered [Spotify had a Java Docker client library](https://github.com/spotify/docker-client).

Since then I've been thinking about rebooting and deeply leveraging Swarm, especially Rackspace's Carina, [such as this](https://getcarina.com/docs/tutorials/minecraft/). That way parents/kids that aren't server-savvy could spin up a public Minecraft container with just a Carina account.

It's funny you say that. This container started as a tiny tech demo to show someone at work how to launch a Java app in Docker (and the kids and I love Minecraft). Since then I point to this and my Elasticsearch container when convincing/explaining Docker at work :) .

**Comment by sshipway** [comment]
I wish I had the time and skill to do the web frontend idea justice; however I suspect I will only be able to run up something too rough to release publicly.  However, summer is coming (well, here in NZ anyway) and so there may be some time ...

**Comment by itzg** [comment]
Built and pushed on Docker Hub
