### ISSUE TITLE
Trouble with Minecraft 1.8.9 Forge 11.15.1

### ISSUE THREAD

**Issue by nigels-com** [itzg/dockerfiles#58]
`-e VERSION=1.8.9 -e TYPE=FORGE -e FORGEVERSION=11.15.1.1722`

For some reason the script is stripping off the *.9* and failing to download the requested 1.8.9/forge version combo.  But with the following hack,it works:

```
--- a/minecraft-server/start-minecraft.sh
+++ b/minecraft-server/start-minecraft.sh
@@ -65,7 +65,7 @@ case "$TYPE" in
     # norm := the official Minecraft version as Forge is tracking it. dropped the third part starting with 1.8
     TYPE=FORGE
     case $VANILLA_VERSION in
-      1.7.*)
+      *)
         norm=$VANILLA_VERSION
       ;;```

It seems *clear to me* that I want a specific known-working version combo for certain mods.

**Comment by itzg** [comment]
Ugh, the Forge's versioning scheme got strange with Minecraft 1.8.x...and since the time I put all that complicated logic in there they seem to have gone back to normal with the three-part versions:

![image](https://cloud.githubusercontent.com/assets/988985/12702811/98250d38-c7f8-11e5-95cd-61043f68187d.png)

This would explain why your change was needed to fix it. I'll go in and trim down a bunch of this code to conform to their new-old version scheme.

**Comment by itzg** [comment]
I have successfully tested the fix I'm about to push with these various combinations of versions:

```
docker run -d -p 25575 -e EULA=TRUE -e VERSION=1.8.9 -e TYPE=FORGE -e FORGEVERSION=11.15.1.1726 mc
docker run -d -p 25575 -e EULA=TRUE -e VERSION=1.7.10 -e TYPE=FORGE -e FORGEVERSION=10.13.4.1614 mc
docker run -d -p 25575 -e EULA=TRUE -e VERSION=1.7.10 -e TYPE=FORGE mc
docker run -d -p 25575 -e EULA=TRUE -e VERSION=1.8.9 -e TYPE=FORGE mc
docker run -d -p 25575 -e EULA=TRUE -e VERSION=1.8 -e TYPE=FORGE mc
```

**Comment by itzg** [comment]
Image `6f7f0cfa96a2` with this fix is now pushed to Docker Hub

**Comment by nigels-com** [comment]
Awesome, thanks.
