### ISSUE TITLE
[minecraft-server] Support server mounts for minecraft data

### ISSUE THREAD

**Issue by jbeda** [itzg/dockerfiles#9]
I'm running your minecraft image with server mounts for the data.  Much easier to ensure I don't accidentally delete data by deleting a data container.

However, it is tricky to do this with the support for running as a non-root user.  The UID used from within the image isn't documented.  Because of this, you need to chown the data directory before starting up the container to some unknown UID.

I was working around this by starting the container as root (`-u 0`) and running `/start`.  The `/start` script was fixing the file permissions on the volume and then starting the server as the `minecraft` user.

This broke today when you removed the `/start` command from the image.

Options to fix it:
* Add `/start` back in and rename/document it.
* Support specifying the UID to use and rewrite the /etc/passwd from within the container.

I'm happy to code and send a PR as you like but wanted to get your thoughts before doing so.

**Comment by itzg** [comment]
Oops, I was feeling nervous removing the `ADD` for that...should have stopped myself :)

Let me do a quick fix by putting that file back into the image, but that would be great if you could help me with the proper fix. Even though running processes in the container non-root is ideal, Docker doesn't yet make that seamless.

One option I was considering today was setting `/start` as the `CMD`, but then leaving out the 

    USER minecraft

to let the image and its `/start` script start out as root. What do you think?

**Comment by itzg** [comment]
Quick fix included in [this build](https://registry.hub.docker.com/u/itzg/minecraft-server/build_id/5652/code/b2wrn62uol8ygryvvcdt7xz/)

**Comment by itzg** [comment]
OK, I did a little more investigation and now I fully comprehend what I had read about non-root users within the container. I also came across [this little section](https://docs.docker.com/articles/dockerfile_best-practices/#user) that I hadn't seen before.

It's all about matching up the **uid** of the user within the container to the host's. I had gotten lucky with testing within *boot2docker* and my bare metal Ubuntu machine since the *docker* user had uid=1000...the *minecraft* user added during the `Dockerfile` build was picking up 1000.

So, another option has revealed itself:
* Adjust the use of `adduser` [here](https://github.com/itzg/dockerfiles/blob/master/minecraft-server/Dockerfile#L10) to explicitly specify the `--uid` to use (stick with 1000?)
* Augment the `-v` section in the `README` with a "requirement" that a user of uid 1000 be the owner of the mapped host directory
* Still remove `/start`, perhaps?

**Comment by itzg** [comment]
...sorry, @jbeda, I had skipped over your second bullet regarding overwriting the `/etc/passwd` uid value. Hmm, that's the most tempting option, just not sure if the startup sequence allows for that.

**Comment by jbeda** [comment]
Thanks for the quick fix :)

I think either would work.  Managing UIDs is tricky in a containerized world.  I'm not sure that lots of folks are running non-root in the dockerized world.

**Comment by adkinss** [comment]
I started playing around with itzg/minecraft-server and ran almost immediately into this user UID issue.  Unless I remap user accounts or build a new server to run minecraft on, it doesn't make sense to force the UID to 1000.  In my case, UID 1000 is already in use by a regular user account and there is no way that I want it to own the minecraft directory tree.

I decided to come to your git repo to possibly look at my own solution, or maybe patch it and do a pull request.  I ran across this open bug, which pretty much hits on the issue I am having.

My suggestion is to simply add a "-e UID=" option to the "docker run" command so that we can pick the UID we want to use.  This makes it easy to work with existing servers that do other things besides run minecraft.

Awesome job, by the way!

**Comment by itzg** [comment]
@adkinss, I agree, having to specifically setup the host server defeats the encapsulation of Docker. I'll about some way to accept a -e arg for the server uid. 

For what it's worth I now run all my minecraft containers without the host attached volume. I enjoy the simplicity and self contained aspect. 

Since we can now 'exec' into containers to modify files, my survey style question to you is: what do you find most useful about host attached volumes for the minecraft container?

And thanks for the support :)

**Comment by jbeda** [comment]
For me, host attached volumes can be placed on a different block device.  They can also be backed up en-masse easily.

I have a VM with 4 minecraft servers running.  They all use `/minecraft/<server-name>` as their data directory.  I just back up `/minecraft` and call it a day.

That being said, I'm looking at switching to spigot and have been playing around with some docker images that support the complex "download minecraft jar and decompile it" flow.

**Comment by adkinss** [comment]
I am not currently using host-attached volumes for minecraft.  I don't think I actually will, since it is easy enough to access the files inside the container and do what I need.  I do wish there was a way to mount a data-only container like a filesystem (i.e. with FUSE or something like qemu-nbd), since it would give similar functionality of host-attached volumes, but still keep the data encapsulated without any dependencies on the OS the container live on.

What I have used host-attached volumes for with great success is having a shared directory that is used by multiple containers.  Each container has different versions of the OS (Ubuntu and CentOS) and different versions of a specific application installed. Each container is ran against the same set of data and is checked to make sure that, even though different versions of OS and application combos are present, they all produce the same expected output.  None-the-less, I could have easily done this with a data-only container and just pointed all the other containers to it... soooooo.... :-)

Anyways, I am still looking at this issue in how to best solve it the UID issue when using host-attached volumes, even if I am not using it in practice.

**Comment by itzg** [comment]
Thanks, both of you, for the feedback.

I have some family stuff keeping me distracted, so yes, @adkinss , we'll see who gets to the solution first :) I appreciate your help.

**Comment by itzg** [comment]
@adkinss or @jbeda , do you mind testing out this latest commit I pushed? Its using the new `-e UID=` option we discussed, but defaults to 1000 to match the prior behavior.

Apparently I haven't needed to use `usermod` that much since I only just now noticed its `--uid` option.

**Comment by itzg** [comment]
Oops, "fixes" is a magic GitHub action word. Let me know if you still see issues with the `-e UID` option.
